nome = str(input('Digite o seu nome completo: ')).strip()
print('Analisando o se nome...')
print('O seu nome em maiúsculas é: {}'.format(nome.upper))
print('O seu nome em minúsculas é: {}'.format(nome.lower))
print('O seu nome contém {} letras'.format(len(nome) - nome.count(' ')))
print('O seu primeiro nome contém {} letras'.format.find(''))